// Command gendocs writes the generated half of crier's documentation:
// docs/configuration/reference/ and the crier.example.yaml at the repository
// root.
//
// Both are generated rather than written because they are the pieces that go
// stale silently: a key added to registry.go and not to the docs is invisible
// until somebody needs it, and a sample config missing a key is a sample that
// teaches the wrong thing. The docs gate regenerates them and fails on a diff,
// so the code and the documentation cannot drift.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yohimik/crier/internal/config"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	if err := run(root); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(root string) error {
	dir := filepath.Join(root, "docs", "configuration", "reference")
	// Removed first so a group that no longer exists does not survive as a
	// file nothing links to.
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	groups := groups()
	for _, g := range groups {
		if len(g.keys) == 0 {
			continue
		}
		if err := os.WriteFile(filepath.Join(dir, g.file), renderGroup(g), 0o644); err != nil {
			return err
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "README.md"), renderIndex(groups), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, "crier.example.yaml"), renderExample(groups), 0o644)
}

// generatedNote is the header every generated file carries.
const generatedNote = "Generated by tools/gendocs. Do not edit; edit internal/config/registry.go."

// group is one page of the reference: a key prefix, the file it lands in, and
// the keys that belong to it.
type group struct {
	prefix string
	file   string
	title  string
	intro  string
	keys   []string
}

// prefixes are the key paths the reference is split on, longest first so a key
// lands in the most specific group that claims it.
//
// The list is structural rather than editorial: every entry is a real prefix in
// the registry, and the per-platform ones are generated from the platform list
// so a new platform gets a page without anybody remembering to add one.
func prefixes() []group {
	out := []group{
		{prefix: "log.", title: "Logging",
			intro: "Where the logs go, and how loud. Logs always go to standard error, so standard output stays a clean channel for results."},
		{prefix: "render.video.", title: "Video rendering",
			intro: "Rendering an animated template into an MP4. ffmpeg does the encoding and is a prerequisite crier does not bundle."},
		{prefix: "render.", title: "Rendering",
			intro: "What is drawn, how large, in which format, and with which fonts."},
		{prefix: "http.", title: "HTTP",
			intro: "The shared client every publisher and stager uses: timeouts and retries."},
		{prefix: "stage.s3.", title: "Staging: S3",
			intro: "Used when `stage.mode` is `s3`."},
		{prefix: "stage.server.tunnel.", title: "Staging: tunnel",
			intro: "Used when `stage.mode` is `server` and the listener has to be reachable from the internet."},
		{prefix: "stage.server.", title: "Staging: local server",
			intro: "Used when `stage.mode` is `server`."},
		{prefix: "stage.", title: "Staging",
			intro: "How a rendered file is given a public URL, for the platforms that fetch rather than accept an upload."},
	}
	for _, p := range config.Platforms {
		out = append(out, group{
			prefix: "publish." + p + ".",
			title:  "Publishing: " + platformTitle(p),
			intro:  "See [the " + platformTitle(p) + " guide](../../publishing/" + p + ".md) for how to get these values.",
		})
	}
	return append(out, group{prefix: "publish.", title: "Publishing",
		intro: "The fan-out itself: which platforms, how many at a time, and the shared caption."})
}

func platformTitle(name string) string {
	switch name {
	case "tiktok":
		return "TikTok"
	case "x":
		return "X"
	case "linkedin":
		return "LinkedIn"
	default:
		return strings.ToUpper(name[:1]) + name[1:]
	}
}

// fileFor turns a key prefix into a file name: dots become dashes.
func fileFor(prefix string) string {
	return strings.ReplaceAll(strings.TrimSuffix(prefix, "."), ".", "-") + ".md"
}

// groups assigns every registry key to exactly one page.
func groups() []group {
	out := prefixes()
	for i := range out {
		out[i].file = fileFor(out[i].prefix)
	}
	assigned := map[string]bool{}
	for i := range out {
		for _, key := range config.Keys() {
			if assigned[key] || !strings.HasPrefix(key, out[i].prefix) {
				continue
			}
			out[i].keys = append(out[i].keys, key)
			assigned[key] = true
		}
		sort.Strings(out[i].keys)
	}
	// A key no prefix claims would be invisible, so it gets a page of its own
	// rather than being dropped.
	var rest []string
	for _, key := range config.Keys() {
		if !assigned[key] {
			rest = append(rest, key)
		}
	}
	if len(rest) > 0 {
		out = append(out, group{
			prefix: "", file: "other.md", title: "Other",
			intro: "Keys that belong to no group above.", keys: rest,
		})
	}
	return out
}

func renderIndex(gs []group) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- %s -->\n\n", generatedNote)
	b.WriteString(`# Configuration reference

Every key crier has, one page per group. How the three layers compose, and
where a relative path resolves against, is in
[the configuration guide](../README.md).

`)
	fmt.Fprintln(&b, "| Group | Keys | What it covers |")
	fmt.Fprintln(&b, "| ----- | ---- | -------------- |")
	for _, g := range gs {
		if len(g.keys) == 0 {
			continue
		}
		prefix := g.prefix
		if prefix == "" {
			prefix = "—"
		} else {
			prefix = "`" + strings.TrimSuffix(prefix, ".") + "`"
		}
		fmt.Fprintf(&b, "| [%s](./%s) | %s | %d |\n", g.title, g.file, prefix, len(g.keys))
	}
	b.WriteString("\nA sample carrying every key with its default is at\n" +
		"[`crier.example.yaml`](../../../crier.example.yaml).\n")
	return b.Bytes()
}

func renderGroup(g group) []byte {
	byKey := config.Descriptors()
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- %s -->\n\n", generatedNote)
	fmt.Fprintf(&b, "# %s\n\n", g.title)
	if g.intro != "" {
		fmt.Fprintf(&b, "%s\n\n", g.intro)
	}
	fmt.Fprintln(&b, "| Key | Type | Default | Description |")
	fmt.Fprintln(&b, "| --- | ---- | ------- | ----------- |")
	for _, key := range g.keys {
		d := byKey[key]
		fmt.Fprintf(&b, "| `%s`<br>`%s`<br>`--%s` | %s | %s | %s |\n",
			d.Key, d.EnvName(), d.FlagName(), typeOf(d), defaultOf(d), describe(d))
	}
	fmt.Fprintln(&b, "\n[All groups](./README.md)")
	return b.Bytes()
}

// renderExample writes a sample config carrying every key.
//
// It is a real file the loader accepts, which is the point: a sample that does
// not parse is worse than no sample, and there is a test that loads this one.
func renderExample(gs []group) []byte {
	byKey := config.Descriptors()
	defaults := config.Defaults()
	values := config.Values(&defaults)

	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n", generatedNote)
	b.WriteString(`#
# Every crier option, with its default. Copy the lines you want into your own
# crier.yaml — this file is a reference rather than a starting point: it turns
# nothing on, and the secrets are placeholders.
#
# The same keys are settable as environment variables (CRIER_ + the key, dots
# and dashes to underscores) and as flags (the key with dots turned into
# dashes). See docs/configuration/README.md.

`)

	// The keys are emitted in one pass over the sorted list so the nesting is
	// built once; the group headings are printed as each group's first key is
	// reached, which keeps the file's order and the reference's identical.
	groupOf := map[string]group{}
	for _, g := range gs {
		for _, key := range g.keys {
			groupOf[key] = g
		}
	}

	all := config.Keys()
	var prevPath []string
	seenGroup := map[string]bool{}

	for _, key := range all {
		g := groupOf[key]
		if !seenGroup[g.file] {
			seenGroup[g.file] = true
		}
		segs := strings.Split(key, ".")
		// Open the levels this key adds.
		common := 0
		for common < len(prevPath) && common < len(segs)-1 && prevPath[common] == segs[common] {
			common++
		}
		for i := common; i < len(segs)-1; i++ {
			fmt.Fprintf(&b, "%s%s:\n", indent(i), segs[i])
		}
		prevPath = segs[:len(segs)-1]

		d := byKey[key]
		fmt.Fprintf(&b, "%s# %s\n", indent(len(segs)-1), d.Usage)
		fmt.Fprintf(&b, "%s%s: %s\n", indent(len(segs)-1), segs[len(segs)-1], yamlValue(d, values[key]))
	}
	return b.Bytes()
}

func indent(depth int) string { return strings.Repeat("  ", depth) }

// yamlValue renders one key's sample value: its default, or a placeholder when
// it is a credential nobody should copy from a sample.
func yamlValue(d config.Descriptor, v any) string {
	if d.Secret {
		return `"<your-` + lastSegment(d.Key) + `>"`
	}
	switch t := v.(type) {
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", t)
	case []string:
		if len(t) == 0 {
			return "[]"
		}
		quoted := make([]string, len(t))
		for i, s := range t {
			quoted[i] = quote(s)
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	case string:
		return quote(t)
	default:
		return quote(fmt.Sprint(v))
	}
}

func lastSegment(key string) string {
	if i := strings.LastIndex(key, "."); i >= 0 {
		return key[i+1:]
	}
	return key
}

// quote always quotes, which is the only way a value like 127.0.0.1:0 or a
// bare "-" survives a YAML parser unchanged.
func quote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

func typeOf(d config.Descriptor) string {
	if d.Path {
		return d.Kind.String() + ", path"
	}
	return d.Kind.String()
}

func defaultOf(d config.Descriptor) string {
	if d.Default == "" {
		return "—"
	}
	return "`" + d.Default + "`"
}

func describe(d config.Descriptor) string {
	out := strings.ReplaceAll(d.Usage, "|", `\|`)
	if d.Secret {
		out += " **Secret**: redacted by `crier config`."
	}
	return out
}
