package config

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// examplePath is crier.example.yaml at the repository root, found from this
// test file's own location so the test does not depend on the working
// directory.
func examplePath(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate the test source")
	}
	return filepath.Join(filepath.Dir(file), "..", "..", "crier.example.yaml")
}

// TestExampleConfigLoads is the gate on the generated sample.
//
// A sample that does not parse is worse than no sample: somebody copies it,
// gets an unknown-key error, and concludes crier is broken. The loader refuses
// a key it has no field for, so loading the file is the whole check.
func TestExampleConfigLoads(t *testing.T) {
	path := examplePath(t)
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("%v (regenerate with: go run ./tools/gendocs)", err)
	}

	res, err := Load(context.Background(), Options{Path: path, Environ: []string{}})
	if err != nil {
		t.Fatalf("crier.example.yaml does not load: %v", err)
	}

	// The sample carries defaults, so what comes out of it has to be the
	// defaults — apart from the secrets, which are placeholders.
	defaults := Defaults()
	want := Values(&defaults)
	got := Values(&res.Config)
	secrets := map[string]bool{}
	for _, d := range Registry() {
		secrets[d.Key] = d.Secret
	}

	for key, wantValue := range want {
		if secrets[key] {
			s, _ := got[key].(string)
			if !strings.HasPrefix(s, "<your-") {
				t.Errorf("%s = %q, want a placeholder rather than a real-looking value", key, s)
			}
			continue
		}
		// Paths in the sample are anchored to the file's directory, like any
		// other config file's, so an empty default is what is compared.
		if sameString(got[key], wantValue) {
			continue
		}
		t.Errorf("%s = %#v, want the default %#v", key, got[key], wantValue)
	}
}

// TestExampleConfigCoversEveryKey checks the sample is complete: a key added to
// the registry without regenerating the sample is a key nobody discovers.
func TestExampleConfigCoversEveryKey(t *testing.T) {
	body, err := os.ReadFile(examplePath(t))
	if err != nil {
		t.Fatal(err)
	}
	text := string(body)
	for _, d := range Registry() {
		leaf := d.Key
		if i := strings.LastIndex(leaf, "."); i >= 0 {
			leaf = leaf[i+1:]
		}
		if !strings.Contains(text, leaf+":") {
			t.Errorf("crier.example.yaml has no line for %s (regenerate with: go run ./tools/gendocs)", d.Key)
		}
		if !strings.Contains(text, "# "+d.Usage) {
			t.Errorf("crier.example.yaml has no comment for %s", d.Key)
		}
	}
	if !strings.HasPrefix(text, "# Generated by tools/gendocs") {
		t.Error("the sample should say it is generated")
	}
}

// TestExampleConfigValidates checks the sample is not only parseable but
// usable: every value in it passes the same validation a real run would.
func TestExampleConfigValidates(t *testing.T) {
	res, err := Load(context.Background(), Options{Path: examplePath(t), Environ: []string{}})
	if err != nil {
		t.Fatal(err)
	}
	if err := Validate(&res.Config); err != nil {
		t.Fatalf("crier.example.yaml does not validate: %v", err)
	}
}

func sameString(a, b any) bool {
	as, aok := a.([]string)
	bs, bok := b.([]string)
	if aok && bok {
		if len(as) != len(bs) {
			return false
		}
		for i := range as {
			if as[i] != bs[i] {
				return false
			}
		}
		return true
	}
	return a == b
}
