// Package configgen writes sample configuration files from the registry.
//
// Both `crier init --full` and the generated crier.example.yaml come from here,
// so the sample a user is handed and the sample in the repository cannot say
// different things — and neither can drift from the keys the code actually
// reads, because both are walks over the same registry.
package configgen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/yohimik/crier/internal/config"
)

// Format is the file format a sample is written in.
type Format string

const (
	// YAML is the default, and the only one that carries comments well.
	YAML Format = "yaml"
	// JSON carries no comments at all.
	JSON Format = "json"
	// TOML carries comments, and needs its tables in a particular order.
	TOML Format = "toml"
)

// Formats are the formats a sample can be written in, in the order they are
// offered.
var Formats = []Format{YAML, JSON, TOML}

// ParseFormat reads a format name.
func ParseFormat(s string) (Format, error) {
	switch Format(strings.ToLower(strings.TrimSpace(s))) {
	case "", YAML, "yml":
		return YAML, nil
	case JSON:
		return JSON, nil
	case TOML:
		return TOML, nil
	default:
		return "", fmt.Errorf("unknown format %q (want yaml, json or toml)", s)
	}
}

// Ext is the file extension a format uses, dot included.
func (f Format) Ext() string {
	if f == "" {
		return ".yaml"
	}
	return "." + string(f)
}

// GeneratedNote is the header a file written by tools/gendocs carries. The
// same file written by `crier init --full` is not checked in, so it says where
// it came from instead.
const GeneratedNote = "Generated by tools/gendocs. Do not edit; edit internal/config/registry.go."

// FullPreamble introduces the complete sample. gendocs prefixes GeneratedNote
// to it; `crier init --full` writes it alone.
const FullPreamble = `Every crier option, with its default. Copy the lines you want into your own
config — this file is a reference rather than a starting point: it turns
nothing on, and the secrets are placeholders.

The same keys are settable as environment variables (CRIER_ + the key, dots
and dashes to underscores) and as flags (the key with dots turned into
dashes). See docs/configuration/README.md.`

// Options configures Sample.
type Options struct {
	// Format is yaml, json or toml.
	Format Format
	// Full writes every key rather than a starter.
	Full bool
	// Header is written above the sample as comments. Empty uses the default
	// for the kind of sample being written.
	Header string
}

// Sample renders a configuration file.
func Sample(o Options) ([]byte, error) {
	format, err := ParseFormat(string(o.Format))
	if err != nil {
		return nil, err
	}
	if !o.Full {
		return starter(format, o.Header), nil
	}
	header := o.Header
	if header == "" {
		header = "Written by `crier init --full`.\n\n" + FullPreamble
	}
	return full(format, header)
}

// --- the complete sample ------------------------------------------------------

// full walks the whole registry.
func full(format Format, header string) ([]byte, error) {
	values := currentValues()
	keys := config.Keys()

	switch format {
	case JSON:
		// JSON carries no comments, so the header is dropped rather than
		// written as something a parser would refuse.
		return marshalJSON(keys, values)
	case TOML:
		return writeTOML(keys, values, header), nil
	default:
		return writeYAML(keys, values, header), nil
	}
}

// currentValues is the default configuration read back as a flat map, with the
// credentials replaced by placeholders nobody should copy from a sample.
func currentValues() map[string]any {
	defaults := config.Defaults()
	out := config.Values(&defaults)
	for _, d := range config.Registry() {
		if d.Secret {
			out[d.Key] = "<your-" + lastSegment(d.Key) + ">"
		}
	}
	return out
}

func lastSegment(key string) string {
	if i := strings.LastIndex(key, "."); i >= 0 {
		return key[i+1:]
	}
	return key
}

// writeYAML emits the nested document, one comment per key.
func writeYAML(keys []string, values map[string]any, header string) []byte {
	byKey := config.Descriptors()
	var b strings.Builder
	writeComments(&b, header, "#")

	var prevPath []string
	for _, key := range keys {
		segs := strings.Split(key, ".")
		common := commonDepth(prevPath, segs)
		for i := common; i < len(segs)-1; i++ {
			fmt.Fprintf(&b, "%s%s:\n", indent(i), segs[i])
		}
		prevPath = segs[:len(segs)-1]

		d := byKey[key]
		depth := len(segs) - 1
		fmt.Fprintf(&b, "%s# %s\n", indent(depth), d.Usage)
		fmt.Fprintf(&b, "%s%s: %s\n", indent(depth), segs[depth], yamlValue(values[key]))
	}
	return []byte(b.String())
}

// writeTOML emits tables. Every scalar of a table has to precede its
// sub-tables, which is why the leaves are gathered per table first.
func writeTOML(keys []string, values map[string]any, header string) []byte {
	byKey := config.Descriptors()
	var b strings.Builder
	writeComments(&b, header, "#")

	// Group the keys by their table path, keeping the tables in sorted order.
	leaves := map[string][]string{}
	var tables []string
	for _, key := range keys {
		i := strings.LastIndex(key, ".")
		table := ""
		if i >= 0 {
			table = key[:i]
		}
		if _, seen := leaves[table]; !seen {
			tables = append(tables, table)
		}
		leaves[table] = append(leaves[table], key)
	}
	sort.Strings(tables)

	for _, table := range tables {
		if table != "" {
			fmt.Fprintf(&b, "\n[%s]\n", table)
		}
		for _, key := range leaves[table] {
			d := byKey[key]
			fmt.Fprintf(&b, "# %s\n", d.Usage)
			fmt.Fprintf(&b, "%s = %s\n", lastSegment(key), tomlValue(values[key]))
		}
	}
	return []byte(b.String())
}

// marshalJSON builds the nested object and indents it.
func marshalJSON(keys []string, values map[string]any) ([]byte, error) {
	root := map[string]any{}
	for _, key := range keys {
		segs := strings.Split(key, ".")
		node := root
		for _, seg := range segs[:len(segs)-1] {
			child, ok := node[seg].(map[string]any)
			if !ok {
				child = map[string]any{}
				node[seg] = child
			}
			node = child
		}
		node[segs[len(segs)-1]] = values[key]
	}
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

func commonDepth(prev, segs []string) int {
	n := 0
	for n < len(prev) && n < len(segs)-1 && prev[n] == segs[n] {
		n++
	}
	return n
}

func indent(depth int) string { return strings.Repeat("  ", depth) }

// writeComments prefixes every line of a block with a comment marker.
func writeComments(b *strings.Builder, text, marker string) {
	if text == "" {
		return
	}
	for _, line := range strings.Split(text, "\n") {
		if line == "" {
			b.WriteString(marker + "\n")
			continue
		}
		b.WriteString(marker + " " + line + "\n")
	}
	b.WriteString("\n")
}

// yamlValue renders one value. Strings are always quoted, which is the only
// way a value like 127.0.0.1:0 or a bare "-" survives a YAML parser unchanged.
func yamlValue(v any) string {
	switch t := v.(type) {
	case bool:
		return fmt.Sprintf("%t", t)
	case int:
		return fmt.Sprintf("%d", t)
	case []string:
		if len(t) == 0 {
			return "[]"
		}
		quoted := make([]string, len(t))
		for i, s := range t {
			quoted[i] = quote(s)
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	case string:
		return quote(t)
	default:
		return quote(fmt.Sprint(v))
	}
}

// tomlValue renders one value in TOML's spelling, which agrees with YAML's for
// everything crier stores.
func tomlValue(v any) string { return yamlValue(v) }

func quote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

// --- the starter --------------------------------------------------------------

// starterHeader is what `crier init` writes above its output.
const starterHeader = `crier configuration.

Run crier from this directory, or from anywhere beneath it, and it finds this
file by walking up — the way git finds a repository. Publishing is what crier
does with no command:

    crier --dry-run     # what would be sent, no network
    crier               # send it

Every key here is also an environment variable (CRIER_RENDER_WIDTH) and a flag
(--render-width). ` + "`crier init --full`" + ` writes every option there is;
` + "`crier config`" + ` shows what a run will actually use.`

// starter is the small commented file `crier init` writes.
//
// It is hand-written rather than generated, because a starter's value is in
// what it leaves out: four keys somebody will edit, and one platform to prove
// the loop works.
func starter(format Format, header string) []byte {
	if header == "" {
		header = starterHeader
	}
	var b strings.Builder

	switch format {
	case JSON:
		b.WriteString(`{
  "render": {
    "template": "template.html",
    "data": "data.yaml",
    "width": 1080,
    "height": 1080,
    "output": "card.png"
  },
  "publish": {
    "caption": "{{ .title }}",
    "telegram": {
      "enabled": false,
      "chat-id": "@your_channel"
    }
  }
}
`)
	case TOML:
		writeComments(&b, header, "#")
		b.WriteString(`[render]
# the Go html/template file to render
template = "template.html"
# a JSON or YAML data file, or "-" to read it from stdin
data = "data.yaml"
width = 1080
height = 1080
# where the image is written
output = "card.png"

[publish]
# the post text; it is a template too, with {{ .Platform }} available
caption = "{{ .title }}"

# One platform to start with. The token is a secret, so it goes in the
# environment rather than in this file:
#
#     export CRIER_PUBLISH_TELEGRAM_TOKEN="123456:ABC-DEF..."
#
# See docs/publishing/ for the other eleven.
[publish.telegram]
enabled = false
chat-id = "@your_channel"
`)
	default:
		writeComments(&b, header, "#")
		b.WriteString(`render:
  # the Go html/template file to render
  template: template.html
  # a JSON or YAML data file, or "-" to read it from stdin
  data: data.yaml
  width: 1080
  height: 1080
  # where the image is written
  output: card.png

publish:
  # the post text; it is a template too, with {{ .Platform }} available
  caption: "{{ .title }}"

  # One platform to start with. The token is a secret, so it goes in the
  # environment rather than in this file:
  #
  #     export CRIER_PUBLISH_TELEGRAM_TOKEN="123456:ABC-DEF..."
  #
  # See docs/publishing/ for the other eleven.
  telegram:
    enabled: false
    chat-id: "@your_channel"
`)
	}
	return []byte(b.String())
}
